spring:
  application:
    name: challenge
  datasource:
    url: jdbc:h2:mem:bankdb
    username: user
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
