spring:
  application:
    name: challenge
  datasource:
    url: jdbc:h2:mem:bankdb
    username: user
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB